[package]
name = "grpc-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.23"
http = "0.2.8"
hyper = { version = "0.14.20", features = ["full"] }
index_list = "0.2.7"
metainfo = "0.6.2"
motore = "0.1.0"
tokio = { version = "1.20.1", features = ["sync", "net"] }
tracing = "0.1.36"
volo-grpc = { git = "https://github.com/cloudwego/volo.git", package = "volo-grpc" }
